package com.zyuniversita.data.local.database.entities

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a user in the application.
 *
 * This entity maps to the `userInfo` table in the Room database.
 * Each user is uniquely identified by an auto-generated `userId`.
 *
 * ## Database Configuration:
 * - **Primary Key:** `userId` is the primary key and is auto-generated by Room.
 *
 * @property userId The unique identifier of the user. Automatically generated by the database.
 * @property username The name or identifier chosen by the user.
 */
@Entity(tableName = "userInfo")
data class UserInfoEntity(
    @PrimaryKey(autoGenerate = true)
    val userId: Int = 0,

    val username: String,
)